// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "MorseMission",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "MorseMission",
            targets: ["AppModule"],
            bundleIdentifier: "com.AppleAcademy.MorseMission",
            teamIdentifier: "5BDWVP493R",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.pink),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .fileAccess(.musicFolder, mode: .readWrite),
                .fileAccess(.pictureFolder, mode: .readWrite)
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
                
            ]
        )
    ]
)
